# Generated by Django 3.1 on 2020-08-22 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(blank=datetime.datetime(2020, 8, 22, 19, 35, 23, 335543), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_date',
            field=models.DateTimeField(blank=datetime.datetime(2020, 8, 22, 19, 35, 23, 335543), verbose_name='date updated'),
        ),
    ]
