# Generated by Django 3.1 on 2020-09-17 12:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0011_auto_20200910_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date updated'),
        ),
        migrations.AddField(
            model_name='task',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 12, 10, 41, 331882), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 12, 10, 41, 331882), verbose_name='date updated'),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_title', models.CharField(max_length=200)),
                ('plan_description', models.CharField(blank=True, max_length=200, null=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2020, 9, 17, 12, 10, 41, 291892), verbose_name='date created')),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2020, 9, 17, 12, 10, 41, 291892), verbose_name='date updated')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='date updated')),
                ('completed', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('archive', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='parent_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.plan'),
        ),
    ]
